import { useState, useCallback } from "react";
import { fileToBase64 } from "../services/photoService";

const VALID_TYPES = [
  "Pothole",
  "Broken Signal",
  "Waterlogging",
  "Road Crack",
  "Missing Manhole",
  "Other",
  "None",
];

// ─── Agent 1: Hazard Verification Prompt ───────────────────────────
const VERIFICATION_PROMPT = `You are a road hazard verification agent for Pakistan. Analyze this photo of a reported road hazard.

Determine:
1. What type of road hazard is visible in the image? Choose from: Pothole, Broken Signal, Waterlogging, Road Crack, Missing Manhole, Other, None
2. How severe is it? Choose from: Low, Medium, High
3. Does the image actually show a road hazard?
4. A confidence score from 0 to 100

If the image does NOT show any road hazard (e.g., it's a selfie, food, random object), set type to "None" and confidence to 0.

Return ONLY valid JSON (no markdown, no explanation):
{"verified_type": "...", "severity": "...", "is_hazard": true/false, "confidence": 0-100, "description": "brief description of what you see"}`;

// ─── Agent 2: AI-Generated Image Detection Prompt ──────────────────
const AI_DETECTION_PROMPT = `You are an AI-generated image detection specialist. Analyze this image carefully for signs that it was generated by AI tools like DALL-E, Midjourney, Stable Diffusion, or similar.

Look for these telltale signs:
- Unnatural texture smoothness or plastic-like surfaces
- Impossible geometry or physically implausible structures
- Repeated patterns or symmetric artifacts
- Distorted or nonsensical text in signs/writing
- Unnatural lighting or shadow inconsistencies
- Uncanny perfection in natural elements (skin, water, clouds)
- Warped edges or melting boundaries between objects
- Unusual depth of field or bokeh patterns
- Too-perfect symmetry in natural scenes
- Anomalies in human hands, fingers, or faces

Return ONLY valid JSON (no markdown, no explanation):
{"is_real": true/false, "confidence": 0-100, "reasoning": "brief explanation of your assessment"}`;

/**
 * Hook that runs two AI agents on an uploaded photo:
 * - Agent 1: Verifies the hazard type and severity from the photo
 * - Agent 2: Detects if the photo is AI-generated
 *
 * Uses Google Gemini Vision API.
 *
 * @returns {{ verify, verifying, verificationResult, verificationError }}
 */
export function usePhotoVerification() {
  const [verifying, setVerifying] = useState(false);
  const [verificationResult, setVerificationResult] = useState(null);
  const [verificationError, setVerificationError] = useState(null);

  const verify = useCallback(async (file, reportedType) => {
    const geminiKey = import.meta.env.VITE_GEMINI_API_KEY || "AQ.Ab8RN6K1q60delvr7cbtOD_680hCEwEoELBcjoNxwsSpWWdNeQ";
    const claudeKey = import.meta.env.VITE_CLAUDE_API_KEY;

    if (!geminiKey && !claudeKey) {
      console.info("No AI API key configured. Skipping photo verification.");
      return null;
    }

    setVerifying(true);
    setVerificationError(null);
    setVerificationResult(null);

    try {
      // Convert image to base64
      const base64Data = await fileToBase64(file);
      const mimeType = file.type || "image/jpeg";

      // Run both agents in parallel
      const [hazardResult, aiDetectionResult] = await Promise.allSettled([
        geminiKey
          ? runGeminiVisionAgent(geminiKey, base64Data, mimeType, buildVerificationPrompt(reportedType))
          : runClaudeVisionAgent(claudeKey, base64Data, mimeType, buildVerificationPrompt(reportedType)),
        geminiKey
          ? runGeminiVisionAgent(geminiKey, base64Data, mimeType, AI_DETECTION_PROMPT)
          : runClaudeVisionAgent(claudeKey, base64Data, mimeType, AI_DETECTION_PROMPT),
      ]);

      // Process Agent 1 result
      let verification = null;
      if (hazardResult.status === "fulfilled" && hazardResult.value) {
        verification = hazardResult.value;
        // Validate the type
        if (!VALID_TYPES.includes(verification.verified_type)) {
          verification.verified_type = "Other";
        }
      }

      // Process Agent 2 result
      let aiDetection = null;
      if (aiDetectionResult.status === "fulfilled" && aiDetectionResult.value) {
        aiDetection = aiDetectionResult.value;
      }

      // Compute overall verification status
      const score = verification?.confidence || 0;
      let status = "unverified";
      if (aiDetection && !aiDetection.is_real && aiDetection.confidence > 70) {
        status = "rejected"; // AI-generated photo
      } else if (score >= 70 && verification?.is_hazard) {
        status = "verified";
      } else if (score >= 30) {
        status = "suspicious";
      } else {
        status = "rejected";
      }

      const combined = {
        // Agent 1 results
        verified_type: verification?.verified_type || "Other",
        severity: verification?.severity || "Medium",
        is_hazard: verification?.is_hazard ?? false,
        verification_score: score,
        verification_description: verification?.description || "",
        verification_status: status,

        // Agent 2 results
        is_ai_generated: aiDetection ? !aiDetection.is_real : false,
        ai_detection_confidence: aiDetection?.confidence || 0,
        ai_detection_reasoning: aiDetection?.reasoning || "",

        // Matching
        matches_reported_type:
          verification?.verified_type?.toLowerCase() === reportedType?.toLowerCase(),
      };

      setVerificationResult(combined);
      return combined;
    } catch (err) {
      console.error("Photo verification failed:", err);
      setVerificationError(err.message);
      return null;
    } finally {
      setVerifying(false);
    }
  }, []);

  const resetVerification = useCallback(() => {
    setVerificationResult(null);
    setVerificationError(null);
  }, []);

  return {
    verify,
    verifying,
    verificationResult,
    verificationError,
    resetVerification,
  };
}

/**
 * Build the verification prompt with the user's reported hazard type.
 */
function buildVerificationPrompt(reportedType) {
  return `${VERIFICATION_PROMPT}\n\nThe user reported this as: "${reportedType || "Unknown"}".\nDoes the photo match their report?`;
}

/**
 * Run a Gemini Vision API call with an image.
 */
async function runGeminiVisionAgent(apiKey, base64Data, mimeType, prompt) {
  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              { text: prompt },
              {
                inline_data: {
                  mime_type: mimeType,
                  data: base64Data,
                },
              },
            ],
          },
        ],
        generationConfig: {
          temperature: 0.1,
          maxOutputTokens: 500,
        },
      }),
    }
  );

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`Gemini Vision API error ${response.status}: ${errorBody}`);
  }

  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text || "";

  // Strip markdown code blocks if present
  const cleaned = text
    .replace(/```json\n?/g, "")
    .replace(/```\n?/g, "")
    .trim();

  return JSON.parse(cleaned);
}

/**
 * Run a Claude Vision API call with an image.
 */
async function runClaudeVisionAgent(apiKey, base64Data, mimeType, prompt) {
  // Map common mime types to Claude-supported media types
  const mediaType = mimeType === "image/webp" ? "image/webp" :
                    mimeType === "image/png" ? "image/png" : "image/jpeg";

  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
      "anthropic-dangerous-direct-browser-access": "true",
    },
    body: JSON.stringify({
      model: "claude-sonnet-4-20250514",
      max_tokens: 500,
      messages: [
        {
          role: "user",
          content: [
            {
              type: "image",
              source: {
                type: "base64",
                media_type: mediaType,
                data: base64Data,
              },
            },
            {
              type: "text",
              text: prompt,
            },
          ],
        },
      ],
    }),
  });

  if (!response.ok) {
    throw new Error(`Claude Vision API error: ${response.status}`);
  }

  const data = await response.json();
  const text = data.content?.[0]?.text || "";
  return JSON.parse(text);
}
